### ISSUE TITLE
Add stepper class to documentation

### ISSUE THREAD

**Issue by SOSANA** [rnosov/react-reveal#26]
Hey guys,

I was digging through your src code and found your Stepper class that I thought was really great to apply to sequenced events for elements.

Any chance you would consider adding this to the documentation so others can be aware of its availability? Seemed like it was a easter egg at first, lol as its not mentioned anywhere that I could see in the docs. Currently applying it to some projects I am working on and thought it was cool feature that was included.

Cheers!

**Comment by SOSANA** [comment]
@rnosov is this a viable request or should I close this issue?

**Comment by rnosov** [comment]
@SOSANA I've been busy last few days but I have some time now to answer your question. 
The stepper class was supposed to be a very cool feature but I had problems with some steps **sometimes** not firing on mobile browsers. It looked to me that I was running into some kind of browser performance optimization / race condition / something else. Since then, I've improved the speed of `react-reveal` substantially and it could be the case that the original problem is no longer there.
Testing the stepper was really maddening experience as you'd be ploughing through a browser race conditions minefield. Also, I was using Context API for the stepper which is being changed so I decided postpone this feature for now.
Right now, you could emulate most of stepper functionality by using `wait` prop on reveal classes. This is how the carousel works on the `react-reveal` homepage for example. The stepper would be a lot more sophisticated solution that would enable many more use cases. If someone is willing help me with this feature it would be really great. If not I might return to it and release it in future anyway.

**Comment by SOSANA** [comment]
Hi @rnosov

Thanks for taking the time to reply back. I haven't tested it in all browsers but I was able to apply it to both chrome and firefox browser, testing it on various mobile devices.  I was able to utilize the step method with timing sequence.

Thought this was a cool example of applying react-reveal...
here is the browser url: https://0ojzp5wlqw.codesandbox.io/
and here is the project url: https://codesandbox.io/s/0ojzp5wlqw

Hoping to battle tested it future in the coming days.

Cheers,

Zach
