### ISSUE TITLE
Different animations for an element based on trigger

### ISSUE THREAD

**Issue by oyeanuj** [rnosov/react-reveal#9]
Hi @rnosov, thank you for putting out this library, looks really cool. I had a quick usage question with the library that I was hoping you could help advice: Similar to [the text in the left side of the demo here](http://davegamache.com/parallax), I was looking to fade in text (or rather paragraphs of text) on scroll and then after it reaches at half the viewport, fade it out again.

Is it possible to use `react-reveal` to combine both the Fade In and Fade Out on the same component based on triggers like viewpoint position or opacity? If not, how would you recommend creating a similar effect with `react-reveal`?

**Comment by rnosov** [comment]
Thanks @oyeanuj, the demo that you linked to is basically a vertical carousel in the fixed postion. They hijack scroll bar in order to control it. I'm about to release a version `1.0` of  `react-reveal` which will include carousel component. You can have a look at the [source code](https://github.com/rnosov/react-reveal/blob/1.0/src/Carousel.js) to get the idea how it could be done.

You can trigger fade out manually by setting `when` prop to `false` in some callback

```jsx
this.state.trigger = true; // in constructor 
<Fade left opposite when={this.state.trigger}><div> ...</div></Fade>
// somewhere  further down
<Fade left onReveal={ () => this.setState({ trigger: false }) }><div> ...</div></Fade>
```
But you won't get the same effect as in demo as you as the elements have to be fixed and locked into carousel. Implementing carousel from scratch might be quite tricky so I suggest to wait for `1.0` release and then use the carousel. You would need to hijack scroll bar yourself though as I'm not going to provide help for that.

**Comment by rnosov** [comment]
`1.0` has been released. It includes a carousel. You can check https://github.com/rnosov/react-reveal/blob/site/src/home/Carousel.js to see how it can be used. I'll post more docs a bit later on how to use the carousel at http://www.react-reveal.com/docs/
